Datasets:
  train:
    root: D:\IFF_data_campaign\cubes\friday_playtime_after
    file_ending: .cu3s
  eval:
    root: D:\IFF_data_campaign\cubes\friday_playtime_after
    file_ending: .cu3s
  imagenet:
    root: ../data/ImageNet_6_channel
    file_ending: .npy
Model:
  checkpoints: best_teacher_6_channel.pth
  model_size: medium
  batch_size: 1
  channel_size: 384
  input_size: 256
  iterations: 50000
  with_bn: false
  in_channels: 6
  use_imgNet_penalty: True
#ImageNet mean and std doubled to have 6 entries
mean: [0.485, 0.456, 0.406, 0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225, 0.229, 0.224, 0.225]
name: Testrun
learning_rate: 0.0001
weight_decay: 0.0001
seed: 42
ckpt_dir: ../data/checkpoints
logger_dir: ../data/logs
max_steps: 70000
max_img_shape: 1500