data_path: ../data/strawberry_dataset/swir
batch_size: 1
name: example_train_name # name of this training run
ckpt_dir: ../data/ckpts # directory to save the checkpoints to
logger_dir: ../data/logs # directory to save the logs / tensorboard files to
max_steps: 200000
pca_channels: 32 # dimension reduction done by the PCA this need to be dividable by 8
cube_channels: 38 # number of input channels
cube_size: [ 200,200 ] # size of the cube this also needs to be dividable by 8
num_classes: 3 # number of classes in the input dataset and model output
white_path: ../data/strawberry_dataset/swir/ref/white_001.cu3s # path to the white reference for the dataset
dark_path: ../data/strawberry_dataset/swir/ref/dark_002.cu3s # path to the dark reference for the dataset
learning_rate: 0.0001
weight_decay: 0.001
seed: 42
num_workers: 5 # number of workers for the torch.dataLoader
mean: [ ]
std: [ ]
normalize: false
sides_to_exclude: [ ]
days_to_exclude: [ 28 ]
strawberry_range: [ 0,220 ] # on which strawberries to train on range
cube_rgb_channels: [ 4,12,25 ] # which channels to use for the RGB representation (only used as a visualization in tensorboard)